### ISSUE TITLE
Undocumented eependency on es2015 transforms

### ISSUE THREAD

**Issue by aldendaniels** [gaearon/react-transform-hmr#40]
@gaearon, thanks for your remarkable work on this project. I know you have a lot on your plate right now, so this is a heads-up, not a complaint.

`react-transform-hmr` will not work without the following babel plugins enabled:
1. `transform-es2015-modules-commonjs`
2. `transform-es2015-classes`

**# 1**  is because the code `react-transform-hmr` generates includes ES6-style imports. Ideally these should be pre-compiled to CommonJS (with option for AMD). 

**# 2** is trickier - it looks like internals of the HMR transform depend on some implementation detail of Babel's class implementation. Running against Chrome without the es6 transform does not work, even though Chrome has native support for es6 classes.

**Comment by jamiebuilds** [comment]
> # 1 is because the code react-transform-hmr generates includes ES6-style imports. Ideally these should be pre-compiled to CommonJS (with option for AMD).

No they shouldn't, you should compile them down yourself.

> # 2 is trickier - it looks like internals of the HMR transform depend on some implementation detail of Babel's class implementation. Running against Chrome without the es6 transform does not work, even though Chrome has native support for es6 classes.

They depended on decorators in 1.x, which has been fixed in the 2.0 beta

**Comment by aldendaniels** [comment]
@thejameskyle - Checking back on on this. Where is the 2.0 beta being developed? I don't see a branch for it? I'd love to remove the classes dependency.

**Comment by gaearon** [comment]
He is talking about Babel plugin. Its 2.0 has been released a while ago.

**Comment by aldendaniels** [comment]
@gaearon - thanks! @thejameskyle, looks like issue #2 still exists post 2.0.
